import type { CoreResponse } from '@bropilot/contracts';
import catalog from '@bropilot/contracts/fixtures/catalog.json';
import valid from '@bropilot/contracts/fixtures/assistant-valid.json';
import missing from '@bropilot/contracts/fixtures/assistant-missing.json';
import conflict from '@bropilot/contracts/fixtures/assistant-conflict.json';
import unknown from '@bropilot/contracts/fixtures/assistant-unknown.json';
import { query } from '../../../packages/core-wasm/bropilot_core_wasm.js';

// Generated by Rust. Identities are transport projections; all domain validation stays in Rust.
const snapshots: Record<string, { worldId: string; revisionId: string }> = {
  'assistant-valid': valid, 'assistant-missing': missing,
  'assistant-conflict': conflict, 'assistant-unknown': unknown,
};
const MAX_HTTP_BODY_BYTES = 1024 * 1024;

function error(code: string, message: string, status: number, headers?: HeadersInit): Response {
  return json({ status: 'error', apiVersion: 1, code, message } satisfies CoreResponse, status, headers);
}
function json(value: unknown, status = 200, headers?: HeadersInit): Response {
  const result = new Headers(headers);
  result.set('content-type', 'application/json; charset=utf-8');
  result.set('cache-control', 'no-store');
  result.set('x-content-type-options', 'nosniff');
  return new Response(JSON.stringify(value), { status, headers: result });
}
function run(input: string): Response {
  const result: CoreResponse = JSON.parse(query(input));
  return json(result, result.status === 'ok' ? 200 : result.code === 'resource_limit' ? 413 : 400);
}
async function boundedBody(request: Request): Promise<string | undefined> {
  if (!request.body) return '';
  const reader = request.body.getReader();
  const chunks: Uint8Array[] = [];
  let length = 0;
  try {
    while (true) {
      const chunk = await reader.read();
      if (chunk.done) break;
      length += chunk.value.byteLength;
      if (length > MAX_HTTP_BODY_BYTES) { await reader.cancel(); return undefined; }
      chunks.push(chunk.value);
    }
  } finally { reader.releaseLock(); }
  const bytes = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; }
  return new TextDecoder().decode(bytes);
}

export default {
  async fetch(request, env): Promise<Response> {
    const path = new URL(request.url).pathname;
    if (!path.startsWith('/api/')) return env.ASSETS.fetch(request);
    try {
      if (path === '/api/v1/examples') {
        if (request.method !== 'GET') return error('method_not_allowed', 'Use GET for example revisions.', 405, { Allow: 'GET' });
        return json(catalog.fixtures.map(fixture => ({
          worldId: snapshots[fixture.id].worldId, revisionId: snapshots[fixture.id].revisionId,
          title: fixture.title, scenario: fixture.description,
        })));
      }
      if (path === '/api/v1/query') {
        if (request.method !== 'POST') return error('method_not_allowed', 'Use POST for domain queries.', 405, { Allow: 'POST' });
        if (request.headers.get('content-type')?.split(';')[0].trim().toLowerCase() !== 'application/json') {
          return error('unsupported_media_type', 'Provide an application/json request.', 415);
        }
        const body = await boundedBody(request);
        if (body === undefined) return error('resource_limit', 'HTTP request exceeds 1048576 bytes.', 413);
        return run(body);
      }
      const match = /^\/api\/v1\/worlds\/([^/]+)\/revisions\/([^/]+)$/.exec(path);
      if (match) {
        if (request.method !== 'GET') return error('method_not_allowed', 'Pinned example revisions are read-only.', 405, { Allow: 'GET' });
        const worldId = decodeURIComponent(match[1]);
        const revisionId = decodeURIComponent(match[2]);
        const snapshot = Object.hasOwn(snapshots, revisionId) ? snapshots[revisionId] : undefined;
        if (!snapshot || snapshot.worldId !== worldId) return error('revision_not_found', 'This pinned example revision is unavailable.', 404);
        return run(JSON.stringify({ apiVersion: 1, snapshot, query: { kind: 'workspace' } }));
      }
      return error('route_not_found', 'This API route is unavailable.', 404);
    } catch (cause) {
      if (cause instanceof URIError) return error('invalid_identity', 'Malformed World or revision identity.', 400);
      console.error(JSON.stringify({ event: 'core_query_failed', error: cause instanceof Error ? cause.name : 'UnknownError' }));
      return error('core_unavailable', 'The domain core could not complete this request.', 500);
    }
  },
} satisfies ExportedHandler<Env>;
