defmodule Bropilot do
  @moduledoc """
  Bropilot: An app that makes apps.

  Three-tier authority model:
    - Spaces (immutable): The 5 fundamental thinking categories
    - Recipe (superuser): Pipeline steps, schemas, prompts, validations
    - Map (user): Project data filled in by going through the pipeline
  """

  alias Bropilot.Spaces

  @doc """
  Initialize a new bropilot project at the given path.
  Creates .bropilot/ with spaces.lock, default recipe, and empty map.
  """
  def init(project_path, opts \\ []) do
    recipe_name = Keyword.get(opts, :recipe, "webapp")
    bropilot_dir = Path.join(project_path, ".bropilot")

    with :ok <- File.mkdir_p(bropilot_dir),
         :ok <- write_spaces_lock(bropilot_dir),
         :ok <- copy_recipe(bropilot_dir, recipe_name),
         :ok <- scaffold_map(bropilot_dir) do
      {:ok, bropilot_dir}
    end
  end

  defp write_spaces_lock(bropilot_dir) do
    lock = Spaces.generate_lock()
    content = "# DO NOT EDIT. Generated by Bropilot core.\n" <> Bropilot.Yaml.encode(lock)
    File.write(Path.join(bropilot_dir, "spaces.lock"), content)
  end

  defp copy_recipe(bropilot_dir, recipe_name) do
    source = recipe_path(recipe_name)
    dest = Path.join(bropilot_dir, "recipe")

    if File.dir?(source) do
      File.cp_r(source, dest)
      :ok
    else
      {:error, {:recipe_not_found, recipe_name}}
    end
  end

  defp scaffold_map(bropilot_dir) do
    map_dir = Path.join(bropilot_dir, "map")

    dirs =
      for space <- Spaces.ids() do
        space_dir = Path.join(map_dir, Atom.to_string(space))
        space_def = Spaces.definition(space)

        subdirs =
          space_def.required_slots
          |> Enum.filter(&(&1.type == :directory))
          |> Enum.map(fn slot ->
            Path.join(space_dir, Atom.to_string(slot.id))
          end)

        [space_dir | subdirs]
      end
      |> List.flatten()

    Enum.each(dirs, &File.mkdir_p/1)

    # Measurement space has sub-validation dirs for each primary space
    for sub <- [:problem, :solution, :work, :live] do
      File.mkdir_p(
        Path.join([map_dir, "measurement", "validation", Atom.to_string(sub)])
      )
    end

    # Knowledge space needs decisions subdir
    File.mkdir_p(Path.join([map_dir, "knowledge", "decisions"]))

    # Problem space needs vibes subdir (recipe-specific but standard in webapp)
    File.mkdir_p(Path.join([map_dir, "problem", "vibes"]))

    # Solution space needs subdirs
    for sub <- ~w(domain flows architecture specs) do
      File.mkdir_p(Path.join([map_dir, "solution", sub]))
    end

    # Knowledge space needs traceability file
    traceability_path = Bropilot.Traceability.file_path(map_dir)
    File.mkdir_p!(Path.dirname(traceability_path))

    unless File.exists?(traceability_path) do
      Bropilot.Yaml.encode_to_file(%{"traceability" => []}, traceability_path)
    end

    :ok
  end

  defp recipe_path(name) do
    Path.join([Application.app_dir(:bropilot, "priv"), "recipes", name])
  end
end
