// Generated by bropilot-contract-gen. Do not edit.

export type Source = { kind: SourceKind, reference: string, };

export type SourceKind = "declared" | "assumption" | "hypothesis" | "observation" | "proposal" | "derived";

export type VersionRef = { id: string, version: string, };

export type ObjectShape = { id: string, kind: string, requiredProperties: Array<string>, };

export type RelationEndpoint = { relationKind: string, fromKinds: Array<string>, toKinds: Array<string>, };

export type RequiredRelation = { ruleId: string, subjectKind: string, relationKind: string, objectKind: string, scopeId: string, };

export type ForbiddenCycle = { ruleId: string, relationKinds: Array<string>, };

export type IncompatibleConstraint = { ruleId: string, left: string, right: string, };

export type WorldTemplate = { id: string, version: string, objectShapes: Array<ObjectShape>, allowedRelationEndpoints: Array<RelationEndpoint>, requiredRelations: Array<RequiredRelation>, forbiddenCycles: Array<ForbiddenCycle>, incompatibleConstraints: Array<IncompatibleConstraint>, requiredRulePacks: Array<RulePackPin>, };

export type Purpose = { statement: string, beneficiaryIds: Array<string>, outcomeIds: Array<string>, };

export type Environment = { id: string, title: string, };

export type ThingCapabilities = { external: boolean, forkable: boolean, observable: boolean, reversible: boolean, };

export type ExternalReference = { system: string, connectionStatus: string, };

export type ThingTemplate = { id: string, version: string, title: string, compatibleWorldTemplates: Array<VersionRef>, inheritsWorldContext: boolean, capabilities: ThingCapabilities, };

export type CompiledRulePack = { id: string, version: string, title: string, requiredForWorldTemplateIds: Array<string>, };

export type StateKind = "desired" | "canonical" | "candidate" | "deployed";

export type Thing = { id: string, kind: string, title: string, revisionId: string, templateRef: VersionRef, capabilities: ThingCapabilities, externalReference?: ExternalReference, source: Source, };

export type ModelObject = { id: string, kind: string, title: string, thingId?: string, parentId?: string, properties: { [key in string]?: string }, source: Source, };

export type ModelRelation = { id: string, kind: string, fromId: string, toId: string, source: Source, };

export type CompletenessStatus = "complete" | "incomplete";

export type CompletenessDeclaration = { scopeId: string, status: CompletenessStatus, source: Source, };

export type TheoryClaim = { id: string, title: string, outcomeId: string, indicatorIds: Array<string>, evaluationIds: Array<string>, source: Source, };

export type Theory = { claims: Array<TheoryClaim>, };

export type MoveSummary = { id: string, title: string, baseRevisionId: string, status: string, };

export type RulePackPin = { id: string, version: string, };

export type WorldSnapshot = { worldId: string, title: string, revisionId: string, template: WorldTemplate, purpose: Purpose, environment: Environment, phase: string, stateKind: StateKind, things: Array<Thing>, thingTemplates: Array<ThingTemplate>, objects: Array<ModelObject>, relations: Array<ModelRelation>, completeness: Array<CompletenessDeclaration>, theory: Theory, moves: Array<MoveSummary>, rulePacks: Array<RulePackPin>, activeConstraints: Array<string>, };

export type Query = { "kind": "workspace" } | { "kind": "readiness" } | { "kind": "children", parentId: string, };

export type CoreRequest = { apiVersion: number, snapshot: WorldSnapshot, query: Query, };

export type ReadinessStatus = "ready" | "blocked" | "unknown";

export type Finding = { ruleId: string, severity: string, message: string, objectIds: Array<string>, factIds: Array<string>, source: Source, };

export type DerivedFact = { id: string, kind: string, fromId: string, toId: string, factIds: Array<string>, source: Source, };

export type OutcomeAssessment = { outcomeId: string, status: string, message: string, };

export type ReadinessEvaluation = { worldId: string, revisionId: string, templateId: string, templateVersion: string, snapshotHash: string, templateHash: string, evaluatorVersion: string, rulePacks: Array<RulePackPin>, status: ReadinessStatus, findings: Array<Finding>, derivedFacts: Array<DerivedFact>, outcomeAssessments: Array<OutcomeAssessment>, };

export type WorkspaceResult = { snapshot: WorldSnapshot, readiness: ReadinessEvaluation, };

export type CoreResult = { "kind": "workspace", snapshot: WorldSnapshot, readiness: ReadinessEvaluation, } | { "kind": "readiness", evaluation: ReadinessEvaluation, } | { "kind": "children", objects: Array<ModelObject>, };

export type CoreResponse = { "status": "ok", apiVersion: number, result: CoreResult, } | { "status": "error", apiVersion: number, code: string, message: string, };

export type Actor = "owner" | "implementer" | "verifier";

export type SourceBundle = { files: { [key in string]?: string }, };

export type HttpContract = { method: string, path: string, status: number, contentType: string, responseShape: string, };

export type WebAppKit = { kitId: string, version: string, entrypoint: string, assetsDirectory: string, requiredAsset: string, health: HttpContract, frontend: HttpContract, backend: HttpContract, runnerRef: string, runnerHash: string, };

export type AssayDefinition = { assayId: string, criterionId: string, method: string, mandatory: boolean, runnerRef: string, runnerHash: string, };

export type AssayPlan = { planId: string, version: string, planHash: string, assays: Array<AssayDefinition>, };

export type MoveStatus = "open" | "promoted";

export type Move = { moveId: string, title: string, baseRevisionId: string, desiredRevisionId: string, contractHash: string, planHash: string, status: MoveStatus, createdBy: Actor, createdAtMs: number, };

export type Candidate = { candidateId: string, moveId: string, desiredRevisionId: string, baseRevisionId: string, source: SourceBundle, sourceDigest: string, contractHash: string, submittedBy: Actor, submittedAtMs: number, };

export type ExecutionStatus = "completed" | "error" | "notRun";

export type AssayResult = "pass" | "fail" | "unknown";

export type AssayObservation = { assayId: string, executionStatus: ExecutionStatus, result: AssayResult, summary: string, raw?: string, };

export type VerificationAggregate = "ready" | "blocked" | "unknown";

export type RunStatus = "queued" | "running" | "completed" | "error";

export type RunLease = { leaseId: string, verifierId: string, claimedAtMs: number, expiresAtMs: number, };

export type AssayEvaluation = { verifierId: string, attempt: number, sourceDigest: string, contractHash: string, planHash: string, buildDigest?: string, observations: Array<AssayObservation>, aggregate: VerificationAggregate, completedAtMs: number, };

export type VerificationRun = { runId: string, candidateId: string, sourceDigest: string, contractHash: string, planHash: string, status: RunStatus, aggregate: VerificationAggregate, attempt: number, activeLease?: RunLease, evaluations: Array<AssayEvaluation>, };

export type WorldRevisionRecord = { revisionId: string, parentRevisionId?: string, candidateId?: string, createdBy: Actor, createdAtMs: number, };

export type IdempotencyReceipt = { requestId: string, commandHash: string, result: WorldCommandResult, };

export type WorldState = { worldId: string, title: string, desired: WorldSnapshot, headRevisionId: string, kit: WebAppKit, assayPlan: AssayPlan, moves: Array<Move>, candidates: Array<Candidate>, runs: Array<VerificationRun>, revisions: Array<WorldRevisionRecord>, receipts: Array<IdempotencyReceipt>, };

export type WorldCommand = { "kind": "createWorld", worldId: string, title: string, runnerHash: string, requestId: string, } | { "kind": "createMove", moveId: string, title: string, requestId: string, } | { "kind": "submitCandidate", moveId: string, candidateId: string, source: SourceBundle, requestId: string, } | { "kind": "startVerification", candidateId: string, requestId: string, } | { "kind": "claimRun", runId: string, leaseId: string, verifierId: string, runnerHash: string, requestId: string, } | { "kind": "completeRun", runId: string, leaseId: string, sourceDigest: string, contractHash: string, planHash: string, buildDigest: string | null, observations: Array<AssayObservation>, requestId: string, } | { "kind": "promote", candidateId: string, expectedHeadRevisionId: string, requestId: string, };

export type WorldCommandRequest = { apiVersion: number, state: WorldState | null, actor: Actor, nowMs: number, command: WorldCommand, };

export type WorldCommandResult = { "kind": "worldCreated", worldId: string, revisionId: string, moveId: string, } | { "kind": "moveCreated", moveId: string, } | { "kind": "candidateSubmitted", candidateId: string, sourceDigest: string, } | { "kind": "verificationStarted", runId: string, reused: boolean, } | { "kind": "runClaimed", runId: string, attempt: number, leaseExpiresAtMs: number, } | { "kind": "runCompleted", runId: string, aggregate: VerificationAggregate, } | { "kind": "candidatePromoted", candidateId: string, revisionId: string, };

export type WorldCommandResponse = { "status": "ok", apiVersion: number, state: WorldState, result: WorldCommandResult, } | { "status": "error", apiVersion: number, code: string, message: string, };
