// Generated by bropilot-contract-gen. Do not edit.

export type Source = { kind: SourceKind, reference: string, };

export type SourceKind = "declared" | "assumption" | "hypothesis" | "observation" | "proposal" | "derived";

export type VersionRef = { id: string, version: string, };

export type ObjectShape = { id: string, kind: string, requiredProperties: Array<string>, };

export type RelationEndpoint = { relationKind: string, fromKinds: Array<string>, toKinds: Array<string>, };

export type RequiredRelation = { ruleId: string, subjectKind: string, relationKind: string, objectKind: string, scopeId: string, };

export type ForbiddenCycle = { ruleId: string, relationKinds: Array<string>, };

export type IncompatibleConstraint = { ruleId: string, left: string, right: string, };

export type WorldTemplate = { id: string, version: string, objectShapes: Array<ObjectShape>, allowedRelationEndpoints: Array<RelationEndpoint>, requiredRelations: Array<RequiredRelation>, forbiddenCycles: Array<ForbiddenCycle>, incompatibleConstraints: Array<IncompatibleConstraint>, requiredRulePacks: Array<RulePackPin>, };

export type Purpose = { statement: string, beneficiaryIds: Array<string>, outcomeIds: Array<string>, };

export type Environment = { id: string, title: string, };

export type ThingCapabilities = { external: boolean, forkable: boolean, observable: boolean, reversible: boolean, };

export type ExternalReference = { system: string, connectionStatus: string, };

export type ThingTemplate = { id: string, version: string, title: string, compatibleWorldTemplates: Array<VersionRef>, inheritsWorldContext: boolean, capabilities: ThingCapabilities, };

export type CompiledRulePack = { id: string, version: string, title: string, requiredForWorldTemplateIds: Array<string>, };

export type StateKind = "desired" | "canonical" | "candidate" | "deployed";

export type Thing = { id: string, kind: string, title: string, revisionId: string, templateRef: VersionRef, capabilities: ThingCapabilities, externalReference?: ExternalReference, source: Source, };

export type ModelObject = { id: string, kind: string, title: string, thingId?: string, parentId?: string, properties: { [key in string]?: string }, source: Source, };

export type ModelRelation = { id: string, kind: string, fromId: string, toId: string, source: Source, };

export type CompletenessStatus = "complete" | "incomplete";

export type CompletenessDeclaration = { scopeId: string, status: CompletenessStatus, source: Source, };

export type TheoryClaim = { id: string, title: string, outcomeId: string, indicatorIds: Array<string>, evaluationIds: Array<string>, source: Source, };

export type Theory = { claims: Array<TheoryClaim>, };

export type MoveSummary = { id: string, title: string, baseRevisionId: string, status: string, };

export type RulePackPin = { id: string, version: string, };

export type WorldSnapshot = { worldId: string, title: string, revisionId: string, template: WorldTemplate, purpose: Purpose, environment: Environment, phase: string, stateKind: StateKind, things: Array<Thing>, thingTemplates: Array<ThingTemplate>, objects: Array<ModelObject>, relations: Array<ModelRelation>, completeness: Array<CompletenessDeclaration>, theory: Theory, moves: Array<MoveSummary>, rulePacks: Array<RulePackPin>, activeConstraints: Array<string>, };

export type Query = { "kind": "workspace" } | { "kind": "readiness" } | { "kind": "children", parentId: string, };

export type CoreRequest = { apiVersion: number, snapshot: WorldSnapshot, query: Query, };

export type ReadinessStatus = "ready" | "blocked" | "unknown";

export type Finding = { ruleId: string, severity: string, message: string, objectIds: Array<string>, factIds: Array<string>, source: Source, };

export type DerivedFact = { id: string, kind: string, fromId: string, toId: string, factIds: Array<string>, source: Source, };

export type OutcomeAssessment = { outcomeId: string, status: string, message: string, };

export type ReadinessEvaluation = { worldId: string, revisionId: string, templateId: string, templateVersion: string, snapshotHash: string, templateHash: string, evaluatorVersion: string, rulePacks: Array<RulePackPin>, status: ReadinessStatus, findings: Array<Finding>, derivedFacts: Array<DerivedFact>, outcomeAssessments: Array<OutcomeAssessment>, };

export type WorkspaceResult = { snapshot: WorldSnapshot, readiness: ReadinessEvaluation, };

export type CoreResult = { "kind": "workspace", snapshot: WorldSnapshot, readiness: ReadinessEvaluation, } | { "kind": "readiness", evaluation: ReadinessEvaluation, } | { "kind": "children", objects: Array<ModelObject>, };

export type CoreResponse = { "status": "ok", apiVersion: number, result: CoreResult, } | { "status": "error", apiVersion: number, code: string, message: string, };
