// Docs emitter (lfp v4.0 stage 1-E). Renders docs/ARCHITECTURE.md, docs/FLOWS.md, docs/AI-FUNCTIONS.md
// and the generated agent/prompt.md from the same sources of truth the app reads: src/kernel.ts
// (KINDS, EDGE_TYPES, LEVELS, INVARIANTS, QUESTIONS), src/ai/registry.ts (AI_FUNCTIONS) and
// src/graph.json (nodes, edges). Never imports src/store.ts or src/ai/index.ts (see the plan's
// Import rules) — this script only needs metadata, not the browser runtime.
//
// Run with plain `node` (Node 24 strips types from .ts imports at runtime — no build step).
// `npm run docs` runs this and is expected to be a no-op diff once docs/ and agent/prompt.md are
// committed; smoke asserts `git diff --quiet docs agent/prompt.md`.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { KINDS, EDGE_TYPES, LEVELS, INVARIANTS, QUESTIONS } from '../src/kernel.ts';
import { AI_FUNCTIONS } from '../src/ai/registry.ts';
import graph from '../src/graph.json' with { type: 'json' };

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const BANNER = '<!-- GENERATED by scripts/emit-docs.mjs — do not edit by hand. Run `npm run docs` to regenerate. -->\n';

// ── graph indices ────────────────────────────────────────────────────────────
const nodeById = Object.fromEntries(graph.nodes.map((n) => [n.id, n]));
const nodesOfKind = (kind) => graph.nodes.filter((n) => n.kind === kind).sort((a, b) => a.id.localeCompare(b.id));
const edgesOfType = (type) => graph.edges.filter((e) => e.type === type);
const outEdges = (type, src) => edgesOfType(type).filter((e) => e.src === src);
const targetsOfKind = (type, src, kind) =>
  outEdges(type, src)
    .map((e) => nodeById[e.dst])
    .filter((n) => n && (!kind || n.kind === kind));

/** Mermaid node/edge ids must be alphanumeric/underscore — map every other char to `_`. */
const mid = (id) => id.replace(/[^A-Za-z0-9_]/g, '_');
/** Mermaid node labels: escape quotes/brackets, keep line breaks explicit. */
const mlabel = (text) => `"${String(text).replace(/"/g, "'").replace(/\n/g, '<br/>')}"`;

// ── ARCHITECTURE.md — deployment diagram ────────────────────────────────────
function deploymentDiagram() {
  const infra = nodesOfKind('infra');
  const externals = nodesOfKind('external');
  const audiences = nodesOfKind('audience');
  const clientInfra = infra.filter((n) => n.props?.role === 'client');
  const serverInfra = infra.filter((n) => ['server', 'cache', 'queue'].includes(n.props?.role));
  const storeInfra = infra.filter((n) => n.props?.role === 'store');

  const hostedBy = (infraId) =>
    outEdges('hosts', infraId)
      .map((e) => nodeById[e.dst]?.title)
      .filter(Boolean);

  const lines = ['```mermaid', 'flowchart LR'];
  const sub = (title, id, nodes, labelFn) => {
    lines.push(`  subgraph ${mid(id)}["${title}"]`);
    for (const n of nodes) lines.push(`    ${mid(n.id)}[${mlabel(labelFn(n))}]`);
    lines.push('  end');
  };
  sub('Audiences', 'audiences', audiences, (n) => n.title);
  sub('Client', 'client', clientInfra, (n) => `${n.title}${hostedBy(n.id).length ? `\nhosts: ${hostedBy(n.id).join(', ')}` : ''}`);
  sub('Server', 'server', serverInfra, (n) => `${n.title}${hostedBy(n.id).length ? `\nhosts: ${hostedBy(n.id).join(', ')}` : ''}`);
  sub('Stores & externals', 'stores', [...storeInfra, ...externals], (n) => n.title);

  // Audiences reach the system through client deployables (derived, not a literal `uses` edge).
  for (const a of audiences) for (const c of clientInfra) lines.push(`  ${mid(a.id)} --> ${mid(c.id)}`);
  // Deployable/external network edges: `uses` between infra/infra or infra/external.
  const infraIds = new Set(infra.map((n) => n.id));
  const externalIds = new Set(externals.map((n) => n.id));
  const isDeployable = (id) => infraIds.has(id) || externalIds.has(id);
  for (const e of edgesOfType('uses')) {
    if (isDeployable(e.src) && isDeployable(e.dst)) lines.push(`  ${mid(e.src)} --> ${mid(e.dst)}`);
  }
  lines.push('```');
  return lines.join('\n');
}

// ── ARCHITECTURE.md — one cell diagram per module ───────────────────────────
function cellDiagram(mod) {
  const contained = targetsOfKind('contains', mod.id, undefined);
  const interfaces = targetsOfKind('exposes', mod.id, 'interface');
  const things = contained.filter((n) => n.kind === 'thing');
  const rules = contained.filter((n) => n.kind === 'rule');
  const events = contained.filter((n) => n.kind === 'event');
  const storeInfra = graph.nodes.filter(
    (n) => n.kind === 'infra' && n.props?.role === 'store' && edgesOfType('uses').some((e) => e.src === mod.id && e.dst === n.id),
  );

  const lines = ['```mermaid', 'flowchart LR'];
  if (interfaces.length) {
    lines.push('  subgraph ports["Ports (interfaces)"]');
    for (const i of interfaces) {
      const io = [i.props?.in ? `in: ${i.props.in}` : null, i.props?.out ? `out: ${i.props.out}` : null].filter(Boolean).join('\n');
      lines.push(`    ${mid(i.id)}[${mlabel(`${i.title}${io ? `\n${io}` : ''}`)}]`);
    }
    lines.push('  end');
  }
  if (rules.length) {
    lines.push('  subgraph circuits["Circuits (rules)"]');
    for (const r of rules) lines.push(`    ${mid(r.id)}(${mlabel(r.title)})`);
    lines.push('  end');
  }
  if (things.length) {
    lines.push('  subgraph entities["Entities (things)"]');
    for (const t of things) lines.push(`    ${mid(t.id)}{{${mlabel(t.title)}}}`);
    lines.push('  end');
  }
  if (events.length) {
    lines.push('  subgraph events["Events"]');
    for (const ev of events) lines.push(`    ${mid(ev.id)}([${mlabel(ev.title)}])`);
    lines.push('  end');
  }
  if (storeInfra.length) {
    lines.push('  subgraph datamodel["Data model (behind)"]');
    for (const s of storeInfra) lines.push(`    ${mid(s.id)}[(${mlabel(s.title)})]`);
    lines.push('  end');
  }

  // One circuit per interface: port -> rules governing its carried things -> those things -> its events -> out.
  for (const i of interfaces) {
    const carried = new Set(targetsOfKind('carries', i.id, 'thing').map((t) => t.id));
    const governingRules = rules.filter((r) => outEdges('governs', r.id).some((e) => carried.has(e.dst)));
    for (const r of governingRules) lines.push(`  ${mid(i.id)} -.governs.-> ${mid(r.id)}`);
    for (const r of governingRules) for (const e of outEdges('governs', r.id)) if (carried.has(e.dst)) lines.push(`  ${mid(r.id)} -.-> ${mid(e.dst)}`);
    for (const ev of targetsOfKind('emits', i.id, 'event')) lines.push(`  ${mid(i.id)} -.emits.-> ${mid(ev.id)}`);
  }
  // Plain governs edges not already drawn as part of a circuit (rules governing things outside any interface's carry set).
  for (const r of rules) {
    for (const e of outEdges('governs', r.id)) {
      const t = nodeById[e.dst];
      if (t && t.kind === 'thing' && things.some((th) => th.id === t.id)) lines.push(`  ${mid(r.id)} --> ${mid(t.id)}`);
    }
  }
  lines.push('```');
  return lines.join('\n');
}

const levelBlurb = (n) => LEVELS.find((l) => l.level === n)?.blurb ?? '';
const kindPlural = (id) => KINDS.find((k) => k.id === id)?.plural ?? id;
const edgeHint = (id) => EDGE_TYPES.find((e) => e.id === id)?.hint ?? '';

function architectureMd() {
  const modules = nodesOfKind('module');
  const out = [
    BANNER,
    '# Architecture\n',
    `## Deployment\n`,
    `${levelBlurb(2)}\n`,
    deploymentDiagram(),
    '',
    `## Cells\n`,
    `${levelBlurb(3)}\n`,
    `Circuits are drawn with \`carries\` (${edgeHint('carries')}), \`governs\` (${edgeHint('governs')}) and \`emits\` (${edgeHint('emits')}) edges: each interface's circuit is its port, the rules governing the things it carries, those things, and the events it emits.\n`,
  ];
  for (const mod of modules) {
    const contained = targetsOfKind('contains', mod.id, undefined);
    const interfaces = targetsOfKind('exposes', mod.id, 'interface');
    const things = contained.filter((n) => n.kind === 'thing');
    const rules = contained.filter((n) => n.kind === 'rule');
    const events = contained.filter((n) => n.kind === 'event');
    const tests = contained.filter((n) => n.kind === 'test');
    out.push(`## ${mod.title}\n`);
    if (mod.description) out.push(`${mod.description}\n`);
    out.push(cellDiagram(mod));
    out.push('');
    out.push(`- **${kindPlural('interface')}:** ${interfaces.length ? interfaces.map((i) => i.title).join(', ') : '(none)'}`);
    out.push(`- **${kindPlural('thing')}:** ${things.length ? things.map((t) => t.title).join(', ') : '(none)'}`);
    out.push(`- **${kindPlural('rule')}:** ${rules.length ? rules.map((r) => r.title).join(', ') : '(none)'}`);
    out.push(`- **${kindPlural('event')}:** ${events.length ? events.map((e) => e.title).join(', ') : '(none)'}`);
    out.push(`- **${kindPlural('test')}:** ${tests.length ? tests.map((t) => t.title).join(', ') : '(none)'}`);
    out.push('');
  }
  out.push('## Invariants\n');
  out.push('Architecture-relevant invariants from the kernel (see the app\'s Reference tab for the full list):\n');
  for (const inv of INVARIANTS) out.push(`- ${inv.text}`);
  out.push('');
  out.push(`_${KINDS.length} kinds, ${EDGE_TYPES.length} edge types, ${LEVELS.length} levels, ${INVARIANTS.length} invariants, ${QUESTIONS.length} kernel questions — see the Reference tab for the live versions._`);
  return out.join('\n');
}

// ── FLOWS.md ─────────────────────────────────────────────────────────────────
function flowsMd() {
  const flows = nodesOfKind('flow');
  const groups = [...new Set(flows.map((f) => f.props?.group ?? '(ungrouped)'))].sort();
  const out = [BANNER, '# Flows\n'];
  for (const group of groups) {
    out.push(`## ${group}\n`);
    for (const f of flows.filter((fl) => (fl.props?.group ?? '(ungrouped)') === group)) {
      out.push(`### ${f.title}\n`);
      out.push(`- **Scope:** ${f.props?.scope ?? '(unspecified)'}`);
      const touched = targetsOfKind('uses', f.id, undefined);
      out.push(`- **Touched nodes:** ${touched.length ? touched.map((n) => `${n.title} (${n.kind})`).join(', ') : '(none)'}`);
      const steps = (f.props?.steps ?? '')
        .split('\n')
        .map((s) => s.trim())
        .filter(Boolean);
      if (steps.length) {
        out.push('- **Steps:**');
        steps.forEach((s, i) => out.push(`  ${i + 1}. ${s}`));
      }
      out.push('');
    }
  }
  return out.join('\n');
}

// ── AI-FUNCTIONS.md ──────────────────────────────────────────────────────────
function aiFunctionsMd() {
  const out = [BANNER, '# AI functions\n'];
  out.push('| id | version | purpose | context needs | feedback | provenance |');
  out.push('| --- | --- | --- | --- | --- | --- |');
  for (const f of AI_FUNCTIONS) {
    const prov = f.source.kind === 'said' ? `said S${f.source.statements.join(', S')}` : `inferred: ${f.source.reason}`;
    out.push(
      `| ${f.id} | ${f.version} | ${f.purpose} | ${f.context.needs.join(', ')} | ${f.feedback.map((fb) => fb.label).join(' / ')} | ${prov} |`,
    );
  }
  out.push('');
  for (const f of AI_FUNCTIONS) {
    out.push(`## ${f.id}\n`);
    out.push(`${f.purpose}\n`);
    out.push(`- **Version:** ${f.version}`);
    out.push(`- **Context needs:** ${f.context.needs.join(', ')}`);
    out.push(`- **Output:** ${f.output}`);
    out.push(`- **Feedback options:** ${f.feedback.map((fb) => fb.label).join(', ')}`);
    out.push('');
    out.push('**Prompt:**\n');
    out.push('```');
    out.push(f.prompt.trim() ? f.prompt : '(prompt pending)');
    out.push('```');
    out.push('');
  }
  return out.join('\n');
}

// ── agent/prompt.md — generated ─────────────────────────────────────────────
// The shared director rules, unchanged from the hand-written version this replaces (kept as a
// constant here so the generator is the single source; edit HEADER_RULES, not agent/prompt.md).
const HEADER_RULES = `You are Bropilot's director. You talk to the user about what is on their main screen, one thing
at a time, and you can point at it, walk through it, and propose changes — all through the tools
below, which are the only way you affect the screen or the graph.

Rules:

- One utterance per turn: call \`say\` or \`ask\`, never both. Use \`sequence\` when you need to show
  several things in order while talking.
- Every data change except \`glossary\` goes through \`stage\` (or \`answer\`, which stages for you) and
  waits for the user to \`commit\` it. Nothing else touches the graph.
- If the user's text plausibly answers \`context.next\`, call \`answer\` with it, then say what got
  staged and that it is waiting for approval.
- \`point\` at things before talking about them.
- When asked what to do next, name \`context.next\` (the next unlocked question) or the top
  \`context.gaps\` item, and say why.
- Keep utterances to two sentences or fewer.
- Quote the user's own words when staging a title or description.
- Call \`read_graph\` before claiming anything that is not already visible in \`context.screen\` —
  do not guess at graph contents.`;

function agentPromptMd() {
  const out = [
    '<!-- GENERATED by scripts/emit-docs.mjs — do not edit. Edit HEADER_RULES there for the shared rules, or src/ai/registry.ts for a function\'s prompt, then run `npm run docs`. -->\n',
    HEADER_RULES,
    '',
    '## Functions',
    '',
  ];
  for (const f of AI_FUNCTIONS) {
    out.push(`### ${f.id}\n`);
    out.push(`**Purpose:** ${f.purpose}\n`);
    out.push(`**Context needs:** ${f.context.needs.join(', ')}\n`);
    out.push('**Prompt:**\n');
    out.push('```');
    out.push(f.prompt.trim() ? f.prompt : '(prompt pending)');
    out.push('```\n');
    out.push(`**Output:** ${f.output}\n`);
  }
  return out.join('\n');
}

// ── write ─────────────────────────────────────────────────────────────────
mkdirSync(join(ROOT, 'docs'), { recursive: true });
writeFileSync(join(ROOT, 'docs', 'ARCHITECTURE.md'), architectureMd());
writeFileSync(join(ROOT, 'docs', 'FLOWS.md'), flowsMd());
writeFileSync(join(ROOT, 'docs', 'AI-FUNCTIONS.md'), aiFunctionsMd());
writeFileSync(join(ROOT, 'agent', 'prompt.md'), agentPromptMd());

console.log('docs emitted: docs/ARCHITECTURE.md, docs/FLOWS.md, docs/AI-FUNCTIONS.md, agent/prompt.md');
