import { chromium } from 'playwright';
const out = process.env.OUT ?? '/tmp';
const b = await chromium.launch({ executablePath: process.env.BIN }); const p = await b.newPage({ viewport: { width: 1500, height: 950 } });
const errors = []; p.on('pageerror', (e) => errors.push(e.message)); p.on('console', (m) => m.type() === 'error' && errors.push(m.text()));
await p.goto('http://localhost:5199/#board'); await p.waitForSelector('.card');
const r = {};
r.cards = await p.locator('.card').count(); r.cols = await p.locator('.col').count(); r.dogfood = await p.locator('.dogfood').innerText();
await p.locator('.card').first().click(); r.inspectorTitle = await p.locator('.inspector h2').innerText();
await p.screenshot({ path: `${out}/board.png` });
await p.locator('nav button', { hasText: 'Path' }).click(); await p.waitForSelector('.q');
r.qStates = await p.locator('.q .q-state').allInnerTexts();
await p.locator('.q', { hasText: 'What must it be able to do' }).click();
await p.fill('textarea', 'Explain the kernel to a newcomer\nRecord a decision with its quote');
await p.locator('button', { hasText: 'Stage effects' }).click(); await p.waitForSelector('.effect');
r.effects = await p.locator('.effect').count();
await p.locator('button', { hasText: /^Commit/ }).click(); await p.waitForTimeout(200);
r.commits = await p.locator('.history li').count();
await p.screenshot({ path: `${out}/path.png` });
await p.locator('nav button', { hasText: 'Board' }).click(); await p.waitForSelector('.card');
r.cardsAfter = await p.locator('.card').count();
await p.locator('nav button', { hasText: 'Path' }).click(); await p.locator('button', { hasText: 'Undo last' }).click(); await p.waitForTimeout(200);
await p.locator('nav button', { hasText: 'Board' }).click(); await p.waitForSelector('.card'); r.cardsAfterUndo = await p.locator('.card').count();
await p.locator('nav button', { hasText: 'Kernel' }).click(); await p.waitForSelector('table'); r.kernelRows = await p.locator('tbody tr').count();
await p.locator('input[type=checkbox]').first().check(); r.inferredRows = await p.locator('tbody tr').count();
await p.screenshot({ path: `${out}/kernel.png`, fullPage: false });
await p.locator('nav button', { hasText: 'Flows' }).click(); await p.locator('.flow').first().click(); r.lit = await p.locator('.obj.lit').count(); r.untouched = await p.locator('.flows .warn').count() ? await p.locator('.flows .warn').innerText() : 'none';
await p.screenshot({ path: `${out}/flows.png` });
r.errors = errors; console.log(JSON.stringify(r, null, 1)); await b.close();
